name: screenshot-every-hour

on:
  schedule:
    - cron: '0 * * * *'  # once per hour (UTC)
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Chromium
        run: playwright install chromium

      - name: Run screenshot script
        run: python screenshot.py

      - name: Commit & push new screenshot to screenshots branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'actions@github.com'
          git fetch origin
          git checkout -B screenshots origin/screenshots
          git add screenshots/
          git commit -m "Screenshot $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push origin screenshots
